<?php
/**
 * WooCommerce option theme
 *
 * @package           5th-Avenue\Option
 * @subpackage        Redux
 * @version 1.0.0
 * @author lifeis.design
 */

defined( 'ABSPATH' ) || exit;

$theme_option_sections['woocommerce']				 = array(
	'title'	 => esc_html__( 'Woocommerce', '5th-avenue' ),
	'id'	 => 'woocommerce',
	'icon'	 => 'el el-shopping-cart',
);
$theme_option_sections['woocommerce-general']		 = array(
	'title'				 => esc_html__( 'WooCommerce General Options', '5th-avenue' ),
	'id'				 => 'woocommerce-general',
	'subsection'		 => true,
	'customizer_width'	 => '450px',
	'fields'			 => array(
		array(
			'id'		 => 'shopping-cart-icon-select',
			'type'		 => 'image_select',
			'title'		 => esc_html__( 'Shopping Cart Icon Style', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Choose the style for the shop icons that are used for cart options all over the website.', '5th-avenue' ),
			'options'	 => array(
				'1'	 => array(
					'alt'	 => esc_html__( 'Default', '5th-avenue' ),
					'title'	 => esc_html__( 'Default', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/bag-icon-01.jpg',
				),
				'2'	 => array(
					'alt'	 => esc_html__( 'Suitcase 1', '5th-avenue' ),
					'title'	 => esc_html__( 'Suitcase 1', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/bag-icon-02.jpg',
				),
				'3'	 => array(
					'alt'	 => esc_html__( 'Suitcase 2', '5th-avenue' ),
					'title'	 => esc_html__( 'Suitcase 2', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/bag-icon-03.jpg',
				),
			),
			'default'	 => '1',
		),
		array(
			'id'			 => 'woocommerce-mini-cart-limit-product',
			'type'			 => 'slider',
			'title'			 => esc_html__( 'Mini Cart Max Products', '5th-avenue' ),
			'subtitle'		 => esc_html__( 'Set the maximum amount of unique products(not qty) that can be show in mini cart', '5th-avenue' ),
			'default'		 => 5,
			'min'			 => 1,
			'step'			 => 1,
			'max'			 => 30,
			'display_value'	 => 'text',
		),
		array(
			'id'		 => 'mini-cart-show-when-added',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show mini cart when product added to cart', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'For ajax add to cart only.', '5th-avenue' ),
			'default'	 => true,
			'on'		 => 'Show',
			'off'		 => 'Hide',
		),
		array(
			'id'		 => 'empty-cart-content-show',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show additional content on empty cart page', '5th-avenue' ),
			'default'	 => false,
			'on'		 => 'Show',
			'off'		 => 'Hide',
		),
		array(
			'id'		 => 'empty-cart-content',
			'type'		 => 'editor',
			'title'		 => esc_html__( 'Empty cart page content', '5th-avenue' ),
			'required'	 => array(
				array( 'empty-cart-content-show', '=', '1' ),
			),
		),
		array(
			'id'		 => 'cart-crossells-products',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show Cros-sells products on Cart page', '5th-avenue' ),
			'default'	 => false,
			'on'		 => 'Show',
			'off'		 => 'Hide',
		),
		array(
			'id'		 => 'product-pages-upsell-products-carousel',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Type Upsell products', '5th-avenue' ),
			'default'	 => false,
			'on'		 => 'Carousel',
			'off'		 => 'Blocks',
		),
		array(
			'id'		 => 'product-pages-related-products-carousel',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Type Related products', '5th-avenue' ),
			'default'	 => false,
			'on'		 => 'Carousel',
			'off'		 => 'Blocks',
		),
		array(
			'id'		 => 'related-products-amount',
			'type'		 => 'text',
			'title'		 => esc_html__( 'Related Products Per Page', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Set how many product to show per page for related, up-sell and cross-sell.', '5th-avenue' ),
			'default'	 => '3',
		),
		array(
			'id'		 => 'related-products-grid',
			'type'		 => 'button_set',
			'title'		 => esc_html__( 'Related, Cross-sell and Up-sell Products Grid', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Set amount of related products per row', '5th-avenue' ),
			'options'	 => array(
				'2'	 => '2',
				'3'	 => '3',
				'4'	 => '4',
				'5'	 => '5',
				'6'	 => '6',
			),
			'default'	 => '3',
		),
	),
);
$theme_option_sections['woocommerce-product-page'] = array(
	'title'				 => esc_html__( 'Product Page Options', '5th-avenue' ),
	'id'				 => 'woocommerce-product-page',
	'desc'				 => esc_html__( 'Following settings will be applied to all product pages.', '5th-avenue' ),
	'subsection'		 => true,
	'customizer_width'	 => '450px',
	'fields'			 => array(
		array(
			'id'		 => 'product-pages-breadcrumbs',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show breadcrumbs', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Enable', '5th-avenue' ),
			'off'		 => esc_html__( 'Disable', '5th-avenue' ),
		),
		array(
			'id'		 => 'product-pages-ajax-addtocart',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Ajax Add to cart on product page', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Enable', '5th-avenue' ),
			'off'		 => esc_html__( 'Disable', '5th-avenue' ),
		),
		array(
			'id'		 => 'product-pages-meta-information',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Meta Information', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Show/Hide product categories, tags, etc. information below add to cart.', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Show', '5th-avenue' ),
			'off'		 => esc_html__( 'Hide', '5th-avenue' ),
		),
		array(
			'id'		 => 'product-pages-social-share',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Social Share Buttons', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Show', '5th-avenue' ),
			'off'		 => esc_html__( 'Hide', '5th-avenue' ),
		),
		array(
			'id'		 => 'product-pages-quantity',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Product Quantity', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Show/Hide product quantity field on product page.', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Show', '5th-avenue' ),
			'off'		 => esc_html__( 'Hide', '5th-avenue' ),
		),
		array(
			'id'	 => 'product-pages-bottom-bar-section-start',
			'type'	 => 'section',
			'title'	 => esc_html__( 'Product Page Bottom Bar', '5th-avenue' ),
			'indent' => true,
		),
		array(
			'id'		 => 'product-page-botom-bar',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show bottom bar', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Sticky bar at the bottom of the product page with price and Add to cart button. It appears on scroll when main Add to cart button isn\'t visible and there still some space to footer', '5th-avenue' ),
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
			'default'	 => true,
		),
		array(
			'id'		 => 'product-page-botom-bar-wishlist',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show wishlist button in bottom bar', '5th-avenue' ),
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
			'default'	 => true,
		),
		array(
			'id'	 => 'product-pages-tabs-section-start',
			'type'	 => 'section',
			'title'	 => esc_html__( 'Product Page Tabs', '5th-avenue' ),
			'indent' => true,
		),
		array(
			'id'		 => 'product-pages-desc-tab-enable',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Enable Description tab', '5th-avenue' ),
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
			'default'	 => true,
		),
		array(
			'id'		 => 'product-pages-info-tab-enable',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Enable Additional Info tab', '5th-avenue' ),
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
			'default'	 => true,
		),
		array(
			'id'		 => 'product-pages-tab-type',
			'type'		 => 'button_set',
			'title'		 => esc_html__( 'Enable Additional Info tab', '5th-avenue' ),
			'options'	 => array(
				'tabs'		 => esc_html__( 'Tabs', '5th-avenue' ),
				'accordions' => esc_html__( 'Accordions', '5th-avenue' ),
			),
			'default'	 => 'tabs',
		),
		array(
			'id'		 => 'product-pages-reviews-position',
			'type'		 => 'button_set',
			'title'		 => esc_html__( 'Reviews block Position', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Place review inside or outside of the tabs.', '5th-avenue' ),
			'options'	 => array(
				'1'	 => esc_html__( 'In Tabs', '5th-avenue' ),
				'2'	 => esc_html__( 'After Content', '5th-avenue' ),
			),
			'default'	 => '1',
		),
		array(
			'id'		 => 'product-pages-size-guide-link-text',
			'type'		 => 'text',
			'required'	 => array( 'product-pages-show-size-guide-link', '=', '1' ),
			'title'		 => esc_html__( 'Size Guide Link text', '5th-avenue' ),
			'default'	 => esc_html__( 'Size Guide', '5th-avenue' ),
		),
		array(
			'id'	 => 'product-pages-slider-section-start',
			'type'	 => 'section',
			'title'	 => esc_html__( 'Product Page Slider', '5th-avenue' ),
			'indent' => true,
		),
		array(
			'id'		 => 'product-pages-product-thumbnails-position',
			'type'		 => 'image_select',
			'title'		 => esc_html__( 'Product thumbnails position', '5th-avenue' ),
			'options'	 => array(
				'no-thumbs'		 => array(
					'alt'	 => esc_html__( 'No Thumbs', '5th-avenue' ),
					'title'	 => esc_html__( 'No Thumbs', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/disable-thumbs.png',
				),
				'thumbs-below'	 => array(
					'alt'	 => esc_html__( 'Below Product image', '5th-avenue' ),
					'title'	 => esc_html__( 'Below Product image', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/thumbs-below.png',
				),
				'thumbs-left'	 => array(
					'alt'	 => esc_html__( 'Left to product image', '5th-avenue' ),
					'title'	 => esc_html__( 'Left to product image', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/thumbs-left.png',
				),
			),
			'default'	 => 'no-thumbs',
		),
		array(
			'id'		 => 'product-pages-thumbnails-first-images',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show "Product image" on product page.', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'If disabled, the image set as "Product image" will be shown on products listing only and not on product page. Useful if you want to show different images on grid and product page.', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Enable', '5th-avenue' ),
			'off'		 => esc_html__( 'Disable', '5th-avenue' ),
		),
		array(
			'id'		 => 'product-pages-image-zoom',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Image zoom on hover', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Enable', '5th-avenue' ),
			'off'		 => esc_html__( 'Disable', '5th-avenue' ),
		),
		array(
			'id'		 => 'product-pages-image-lightbox',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Product images fullscreen lightbox', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Enable', '5th-avenue' ),
			'off'		 => esc_html__( 'Disable', '5th-avenue' ),
		),
		array(
			'id'	 => 'product-pages-arrows-section-start',
			'type'	 => 'section',
			'title'	 => esc_html__( 'Product Page Arrows', '5th-avenue' ),
			'indent' => true,
		),
		array(
			'id'		 => 'product-pages-next-prev-product-arrows-enable',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Next product Arrows', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'You can show count of product images in carousel slider and current position.', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Enabled', '5th-avenue' ),
			'off'		 => esc_html__( 'Disabled', '5th-avenue' ),
		),
		array(
			'id'		 => 'product-pages-next-prev-product-arrows-position',
			'type'		 => 'button_set',
			'required'	 => array( 'product-pages-next-prev-product-arrows-enable', '=', '1' ),
			'title'		 => esc_html__( 'Next/Prev product arrows position', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Choose position for next/prev product arrows.', '5th-avenue' ),
			'options'	 => array(
				'1'	 => esc_html__( 'Title Area', '5th-avenue' ),
				'2'	 => esc_html__( 'Screen edges', '5th-avenue' ),
			),
			'default'	 => '1',
		),
		array(
			'id'		 => 'product-pages-product-image-arrows',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Product Image Slider Arrows', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Show arrows for product image slider.', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Enabled', '5th-avenue' ),
			'off'		 => esc_html__( 'Disabled', '5th-avenue' ),
		),
		array(
			'id'	 => 'product-pages-layout-section-start',
			'type'	 => 'section',
			'title'	 => esc_html__( 'Product Page Layout Settings', '5th-avenue' ),
			'indent' => true,
		),
		array(
			'id'		 => 'product-pages-layout',
			'type'		 => 'image_select',
			'subtitle'	 => esc_html__( 'Standard layout will display image and description within the website container. Split Layouts split the entire screen width to image and product information block. If split layout choosed sidebars will be moved below the product information section.', '5th-avenue' ),
			'title'		 => esc_html__( 'Product Pages Layout', '5th-avenue' ),
			'options'	 => array(
				'1'	 => array(
					'alt'	 => esc_html__( 'Standard', '5th-avenue' ),
					'title'	 => esc_html__( 'Standard', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/product-default.png',
				),
				'6'	 => array(
					'alt'	 => esc_html__( 'Standard Full Width', '5th-avenue' ),
					'title'	 => esc_html__( 'Standard Full Width', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/product-fullwidth.png',
				),
				'2'	 => array(
					'alt'	 => esc_html__( 'Small width', '5th-avenue' ),
					'title'	 => esc_html__( 'Small width', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/product-small.png',
				),
				'3'	 => array(
					'alt'	 => esc_html__( 'Small width Title Top', '5th-avenue' ),
					'title'	 => esc_html__( 'Small width Title Top', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/product-title-top.png',
				),
				'7'	 => array(
					'alt'	 => esc_html__( 'Sticky Full Width', '5th-avenue' ),
					'title'	 => esc_html__( 'Sticky Full Width', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/product-fullwidth-sticky.png',
				),
			),
			'default'	 => '1',
		),
		array(
			'id'		 => 'product-pages-description-alignment',
			'type'		 => 'image_select',
			'subtitle'	 => esc_html__( 'You can adjust alignment of the product information content block.', '5th-avenue' ),
			'title'		 => esc_html__( 'Product Pages Description Alignment', '5th-avenue' ),
			'options'	 => array(
				'left'	 => array(
					'alt'	 => esc_html__( 'Left', '5th-avenue' ),
					'title'	 => esc_html__( 'Left', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/prod-desc-top.png',
				),
				'center' => array(
					'alt'	 => esc_html__( 'Centered', '5th-avenue' ),
					'title'	 => esc_html__( 'Centered', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/product-desc-centered.png',
				),
			),
			'default'	 => 'left',
		),
		array(
			'id'		 => 'product-pages-description-vertical-alignment',
			'type'		 => 'image_select',
			'title'		 => esc_html__( 'Product Pages Description Vertical Alignment', '5th-avenue' ),
			'options'	 => array(
				'top'	 => array(
					'alt'	 => esc_html__( 'Top', '5th-avenue' ),
					'title'	 => esc_html__( 'Top', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/prod-desc-top.png',
				),
				'middle' => array(
					'alt'	 => esc_html__( 'Middle', '5th-avenue' ),
					'title'	 => esc_html__( 'Middle', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/prod-desc-middle.png',
				),
			),
			'default'	 => 'top',
		),
		array(
			'id'		 => 'product-pages-buttons-layout',
			'type'		 => 'image_select',
			'title'		 => esc_html__( 'Product Pages Buttons Layout', '5th-avenue' ),
			'options'	 => array(
				'1'	 => array(
					'alt'	 => esc_html__( 'In one line', '5th-avenue' ),
					'title'	 => esc_html__( 'In one line', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/prod-buttons-1.png',
				),
				'2'	 => array(
					'alt'	 => esc_html__( 'All elements on a new line', '5th-avenue' ),
					'title'	 => esc_html__( 'All elements on a new line', '5th-avenue' ),
					'img'	 => get_template_directory_uri() . '/inc/options/assets/img/prod-buttons-2.png',
				),
			),
			'default'	 => '1',
		),
	),
);


$theme_option_sections['woocommerce-shop-filters'] = array(
	'title'				 => esc_html__( 'Product Filters', '5th-avenue' ),
	'id'				 => 'woocommerce-shop-filters',
	'subsection'		 => true,
	'customizer_width'	 => '450px',
	'fields'			 => array(
		array(
			'id'		 => 'shop-page-product-filters',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show WooCommerce Filters', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
		),
		array(
			'id'		 => 'shop-page-product-filters-position',
			'type'		 => 'select',
			'title'		 => esc_html__( 'WooCommerce Filters Position', '5th-avenue' ),
			'desc'		 => esc_html__( 'Adaptive filters will be cenetered if they are alone or aligned to the left if there is woocommerce sorting.', '5th-avenue' ),
			'options'	 => array(
				'after-left'	 => esc_html__( 'After Title area on the Left', '5th-avenue' ),
				'after-adaptive' => esc_html__( 'After Title area Adaptive', '5th-avenue' ),
				'after-centered' => esc_html__( 'After Title area Centered', '5th-avenue' ),
				'title-area'	 => esc_html__( 'In Title area', '5th-avenue' ),
			),
			'default'	 => '1',
			'required'	 => array( 'shop-page-product-filters', '=', '1' ),
		),
		array(
			'id'		 => 'shop-page-product-filters-style',
			'type'		 => 'select',
			'title'		 => esc_html__( 'WooCommerce Filters Style', '5th-avenue' ),
			'options'	 => array(
				'1'	 => esc_html__( 'Drop Downs', '5th-avenue' ),
				'2'	 => esc_html__( 'Slideout', '5th-avenue' ),
			),
			'default'	 => '1',
			'required'	 => array( 'shop-page-product-filters', '=', '1' ),
		),
		array(
			'id'		 => 'shop-page-product-filter-category',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show WooCommerce Filter by Category', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
			'required'	 => array( 'shop-page-product-filters', '=', '1' ),
		),
		array(
			'id'		 => 'shop-page-product-filter-attributes',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show WooCommerce Filter by Attributes', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
			'required'	 => array( 'shop-page-product-filters', '=', '1' ),
		),
		array(
			'id'		 => 'shop-page-product-filter-tag',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show WooCommerce Filter by Tag', '5th-avenue' ),
			'default'	 => false,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
			'required'	 => array( 'shop-page-product-filters', '=', '1' ),
		),
		array(
			'id'		 => 'shop-page-product-filter-price',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show WooCommerce Filter by Price', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
			'required'	 => array( 'shop-page-product-filters', '=', '1' ),
		),
		array(
			'id'		 => 'shop-page-product-filter-element-all',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show "All" in WooCommerce Filter', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
			'required'	 => array( 'shop-page-product-filters', '=', '1' ),
		),
		array(
			'id'		 => 'shop-page-product-filter-order',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show Default WooCommerce Orders', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
			'required'	 => array( 'shop-page-product-filters', '=', '1' ),
		),
		array(
			'id'		 => 'shop-page-hide-default-order',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Hide Default WooCommerce Orders', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Remove default WooCommerce Orders that allow you to sort products by newness, popularity, etc.', '5th-avenue' ),
			'default'	 => false,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
			'required'	 => array( 'shop-page-product-filters', '=', '0' ),
		),
	),
);


$theme_option_sections['woocommerce-shop-listing'] = array(
	'title'				 => esc_html__( 'Shop Listing', '5th-avenue' ),
	'id'				 => 'woocommerce-shop-listing',
	'subsection'		 => true,
	'customizer_width'	 => '450px',
	'fields'			 => array(
		array(
			'id'		 => 'products-layout',
			'type'		 => 'select',
			'title'		 => esc_html__( 'Sidebars configuration', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Set sidebars for product pages.', '5th-avenue' ),
			'options'	 => array(
				'no-sidebar'				 => esc_html__( 'Standard - No Sidebars', '5th-avenue' ),
				'left-sidebar'				 => esc_html__( 'Left Sidebar', '5th-avenue' ),
				'right-sidebar'				 => esc_html__( 'Right Sidebar', '5th-avenue' ),
				'fullwidth'					 => esc_html__( 'Fullwdith - No Sidebars', '5th-avenue' ),
				'fullwidth-left-sidebar'	 => esc_html__( 'Fullwdith - Left Sidebar', '5th-avenue' ),
				'fullwidth-right-sidebar'	 => esc_html__( 'Fullwdith - Right Sidebar', '5th-avenue' ),
			),
			'default'	 => 'no-sidebar',
			'select2'	 => array( 'allowClear' => false ),
		),
		// Sidebar.
		array(
			'id'		 => 'products-sidebar',
			'required'	 => array(
				'products-layout',
				'=',
				array( 'left-sidebar', 'right-sidebar', 'fullwidth-left-sidebar', 'fullwidth-right-sidebar' ),
			),
			'type'		 => 'select',
			'data'		 => 'sidebar',
			'title'		 => esc_html__( 'Choose Sidebar', '5th-avenue' ),
		),
		// Sidebar layout.
		array(
			'id'		 => 'products-sidebar-size',
			'type'		 => 'button_set',
			'title'		 => esc_html__( 'Sidebar size', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Choose sidebar size for shop page (catalog)', '5th-avenue' ),
			'options'	 => array(
				'4'	 => '1/3',
				'3'	 => '1/4',
			),
			'default'	 => '3',
		),
		array(
			'id'		 => 'shop-listing-pagination-type',
			'type'		 => 'select',
			'title'		 => esc_html__( 'Pagination Type', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Choose to divide shop posts by pages or load them while scrolling the page', '5th-avenue' ),
			'options'	 => array(
				'default'		 => esc_html__( 'Default', '5th-avenue' ),
				'loadmore'		 => esc_html__( 'Load more button', '5th-avenue' ),
				'infinitescroll' => esc_html__( 'Infinite Scroll', '5th-avenue' ),
			),
			'default'	 => 'loadmore',
			'select2'	 => array( 'allowClear' => false ),
		),
		// Load In Animation.
		array(
			'id'		 => 'shop-listing-loadin-animation',
			'type'		 => 'select',
			'title'		 => esc_html__( 'Load In Animation', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Choose animation effect for product on page scroll', '5th-avenue' ),
			'options'	 => array(
				'none'			 => esc_html__( 'None', '5th-avenue' ),
				'fadein'		 => esc_html__( 'Fade in', '5th-avenue' ),
				'fadeinbottom'	 => esc_html__( 'Fade in from bottom', '5th-avenue' ),
			),
			'default'	 => 'fadeinbottom',
			'select2'	 => array( 'allowClear' => false ),
		),
		array(
			'id'		 => 'shop-page-products-grid-centered',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Center products in catalog', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
		),
		array(
			'id'		 => 'shop-page-products-grid-mobile',
			'type'		 => 'button_set',
			'title'		 => esc_html__( 'Shop page Products grid on mobile', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Set amount of products per row on mobile', '5th-avenue' ),
			'options'	 => array(
				'2'	 => '2',
				'1'	 => '1',
			),
			'default'	 => '2',
		),
		array(
			'id'		 => 'shop-page-products-max-width',
			'type'		 => 'text',
			'title'		 => esc_html__( 'Product Max Width', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Set max width of the products on listing.', '5th-avenue' ),
			'default'	 => '',
		),
		array(
			'id'		 => 'shop-page-products-per-page',
			'type'		 => 'text',
			'title'		 => esc_html__( 'Products Per Page', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Set how many product to show per page on shop page and categories.', '5th-avenue' ),
			'default'	 => '20',
		),
		array(
			'id'		 => 'shop-page-products-thumbnail-styles',
			'type'		 => 'select',
			'title'		 => esc_html__( 'Product Layout and hovers', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Choose the layout and animations for product item in listing', '5th-avenue' ),
			'options'	 => array(
				'default-simple'	 => esc_html__( 'Default, Simple hover', '5th-avenue' ),
				'default-moveup'	 => esc_html__( 'Default, Move Up', '5th-avenue' ),
				'bottom-line-simple' => esc_html__( 'Bottom Line(quickview and wishlist), Simple hover', '5th-avenue' ),
				'bottom-line-moveup' => esc_html__( 'Bottom Line(quickview and wishlist), Move Up', '5th-avenue' ),
				'shadow-box'		 => esc_html__( 'Shadow box', '5th-avenue' ),
				'shadow-box-hover'	 => esc_html__( 'Naked, Shadow box on hover', '5th-avenue' ),
			),
			'default'	 => 'default-simple',
		),
		array(
			'id'		 => 'shop-page-products-thumbnail-type',
			'type'		 => 'select',
			'title'		 => esc_html__( 'Product Thumbnail Type', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'You can show product images slider or second image on product hover.', '5th-avenue' ),
			'options'	 => array(
				'1'	 => esc_html__( 'Single Image', '5th-avenue' ),
				'2'	 => esc_html__( 'Second Image on Hover', '5th-avenue' ),
			),
			'default'	 => '2',
		),
		array(
			'id'		 => 'shop-page-products-carousel-thumbnail-type',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Enable Thumbnails Carousel', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
		),
		array(
			'id'		 => 'shop-page-products-thumbnail-carousel-arrows',
			'type'		 => 'switch',
			'required'	 => array( 'shop-page-products-thumbnail-type', '=', '3' ),
			'title'		 => esc_html__( 'Show Carousel Arrows', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
		),
		array(
			'id'		 => 'shop-page-products-thumbnail-carousel-dots',
			'required'	 => array( 'shop-page-products-thumbnail-type', '=', '3' ),
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show Carousel Dots', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
		),
		array(
			'id'		 => 'shop-page-details-alignment',
			'type'		 => 'button_set',
			'title'		 => esc_html__( 'Product Details Alignment', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Alignment for product information on shop page such as product title, price, etc.', '5th-avenue' ),
			'options'	 => array(
				'left'	 => esc_html__( 'Left', '5th-avenue' ),
				'center' => esc_html__( 'Center', '5th-avenue' ),
				'right'	 => esc_html__( 'Right', '5th-avenue' ),
			),
			'default'	 => 'center',
		),
		array(
			'id'		 => 'shop-page-grid-elements-section-start',
			'type'		 => 'section',
			'title'		 => esc_html__( 'Product Listing Elements', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Choose what elements to show on product listing.', '5th-avenue' ),
			'indent'	 => true,
		),
		array(
			'id'		 => 'shop-page-elements-addtocart',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show Add to Cart link', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
		),
		array(
			'id'		 => 'shop-page-elements-addtocart-hover',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show Add to Cart on hover', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
		),
		array(
			'id'		 => 'shop-page-elements-category',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show product categories', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
		),
		array(
			'id'		 => 'shop-page-quickview',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Enable Quickview', '5th-avenue' ),
			'default'	 => false,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
		),
		array(
			'id'		 => 'shop-page-quickview-button-sticky',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Quickview - Sticky add to cart button', '5th-avenue' ),
			'default'	 => false,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
		),
		array(
			'id'		 => 'shop-page-quickview-text',
			'type'		 => 'text',
			'title'		 => esc_html__( 'Quickview link text', '5th-avenue' ),
			'default'	 => 'Quick view',
		),
		array(
			'id'		 => 'shop-page-quickview-icon',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show Quickview icon', '5th-avenue' ),
			'default'	 => false,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
		),
		array(
			'id'		 => 'shop-page-override_ti_wishlist',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Override the output of TI Wishlist button', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Show wishlist text and icon in bottom line on hover', '5th-avenue' ),
			'default'	 => true,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
		),
		array(
			'id'	 => 'shop-page-grid-banners',
			'type'	 => 'section',
			'title'	 => esc_html__( 'Product Listing Banners', '5th-avenue' ),
			'indent' => true,
		),
		array(
			'id'		 => 'shop-page-grid-banner-enabled1',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show first banner in grid', '5th-avenue' ),
			'default'	 => false,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
		),
		array(
			'id'		 => 'shop-page-grid-banner-position1',
			'type'		 => 'text',
			'title'		 => esc_html__( 'First Banner Position', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Set product number after which the banner will be shown.', '5th-avenue' ),
			'default'	 => '',
			'required'	 => array(
				array( 'shop-page-grid-banner-enabled1', '=', '1' ),
			),
		),
		array(
			'id'		 => 'grid-banner-background-1',
			'type'		 => 'background',
			'title'		 => esc_html__( 'First Banner Background', '5th-avenue' ),
			'default'	 => array(
				'background-color'		 => '#f7f7f6',
				'background-repeat'		 => 'no-repeat',
				'background-position'	 => 'center center',
				'background-size'		 => 'cover',
				'background-attachment'	 => 'scroll',
			),
			'required'	 => array(
				array( 'shop-page-grid-banner-enabled1', '=', '1' ),
			),
		),
		array(
			'id'		 => 'shop-page-grid-banner1',
			'type'		 => 'editor',
			'title'		 => esc_html__( 'First Banner Content', '5th-avenue' ),
			'required'	 => array(
				array( 'shop-page-grid-banner-enabled1', '=', '1' ),
			),
		),
		array(
			'id'		 => 'shop-page-grid-banner-valign1',
			'type'		 => 'select',
			'title'		 => esc_html__( 'First Banner Content Vertical Align', '5th-avenue' ),
			'options'	 => array(
				'center' => esc_html__( 'Center', '5th-avenue' ),
				'top'	 => esc_html__( 'Top', '5th-avenue' ),
			),
			'default'	 => 'center',
			'required'	 => array(
				array( 'shop-page-grid-banner-enabled1', '=', '1' ),
			),
		),
		array(
			'id'		 => 'shop-page-grid-banner-enabled2',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show second banner in grid', '5th-avenue' ),
			'default'	 => false,
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
		),
		array(
			'id'		 => 'shop-page-grid-banner-position2',
			'type'		 => 'text',
			'title'		 => esc_html__( 'Second Banner Position', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Set product number after which the banner will be shown.', '5th-avenue' ),
			'default'	 => '',
			'required'	 => array(
				array( 'shop-page-grid-banner-enabled2', '=', '1' ),
			),
		),
		array(
			'id'		 => 'grid-banner-background-2',
			'type'		 => 'background',
			'title'		 => esc_html__( 'Second Banner Background', '5th-avenue' ),
			'default'	 => array(
				'background-color'		 => '#f7f7f6',
				'background-repeat'		 => 'no-repeat',
				'background-position'	 => 'center center',
				'background-size'		 => 'cover',
				'background-attachment'	 => 'scroll',
			),
			'required'	 => array(
				array( 'shop-page-grid-banner-enabled2', '=', '1' ),
			),
		),
		array(
			'id'		 => 'shop-page-grid-banner2',
			'type'		 => 'editor',
			'title'		 => esc_html__( 'Second Banner Content', '5th-avenue' ),
			'required'	 => array(
				array( 'shop-page-grid-banner-enabled2', '=', '1' ),
			),
		),
		array(
			'id'		 => 'shop-page-grid-banner-valign2',
			'type'		 => 'select',
			'title'		 => esc_html__( 'Second Banner Content Vertical Align', '5th-avenue' ),
			'options'	 => array(
				'center' => esc_html__( 'Center', '5th-avenue' ),
				'top'	 => esc_html__( 'Top', '5th-avenue' ),
			),
			'default'	 => 'center',
			'required'	 => array(
				array( 'shop-page-grid-banner-enabled2', '=', '1' ),
			),
		),
	),
);

$theme_option_sections['products-meta-options-title'] = array(
	'title'				 => esc_html__( 'Shop Page Title Area', '5th-avenue' ),
	'id'				 => 'products-meta-options-title',
	'subsection'		 => true,
	'customizer_width'	 => '450px',
	'fields'			 => array(
		array(
			'id'		 => 'products-titlearea-show',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show Title Area', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Enable to show page title and breadcrumbs.', '5th-avenue' ),
			'on'		 => esc_html__( 'Enabled', '5th-avenue' ),
			'off'		 => esc_html__( 'Disabled', '5th-avenue' ),
			'default'	 => true,
		),
		array(
			'id'		 => 'products-titlearea-type',
			'type'		 => 'select',
			'title'		 => esc_html__( 'Page Title Type', '5th-avenue' ),
			'required'	 => array( 'products-titlearea-show', '=', '1' ),
			'options'	 => array(
				'standard'	 => esc_html__( 'Standard', '5th-avenue' ),
				'hero'		 => esc_html__( 'Hero', '5th-avenue' ),
				'revslider'	 => esc_html__( 'Slider', '5th-avenue' ),
			),
			'default'	 => 'standard',
		),
		array(
			'id'		 => 'products-titlearea-categories',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show Product Categories in Title Area', '5th-avenue' ),
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
			'default'	 => true,
			'required'	 => array(
				array( 'products-titlearea-type', '!=', 'revslider' ),
				array( 'products-titlearea-show', '=', '1' ),
			),
		),
		array(
			'id'		 => 'products-titlearea-categories-all',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show All link in Product Categories in Title Area', '5th-avenue' ),
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
			'default'	 => false,
			'required'	 => array(
				array( 'products-titlearea-categories', '=', '1' ),
			),
		),
		array(
			'id'		 => 'products-titlearea-breadcrumbs',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show breadcrumbs', '5th-avenue' ),
			'required'	 => array(
				array( 'products-titlearea-type', '!=', 'revslider' ),
				array( 'products-titlearea-show', '=', '1' ),
			),
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
			'default'	 => false,
		),
		array(
			'id'		 => 'products-titlearea-title',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show page title', '5th-avenue' ),
			'required'	 => array(
				array( 'products-titlearea-type', '!=', 'revslider' ),
				array( 'products-titlearea-show', '=', '1' ),
			),
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
			'default'	 => true,
		),
		array(
			'id'		 => 'products-titlearea-text-color-style',
			'type'		 => 'select',
			'title'		 => esc_html__( 'Title Area Text Color Style', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Choose the text colors style to fit background image. This option affect additional content and breadcrumbs.', '5th-avenue' ),
			'required'	 => array(
				array( 'products-titlearea-type', '=', 'hero' ),
				array( 'products-titlearea-show', '=', '1' ),
			),
			'options'	 => array(
				'default'	 => esc_html__( 'Default', '5th-avenue' ),
				'white'		 => esc_html__( 'Light', '5th-avenue' ),
			),
			'default'	 => 'default',
		),
		array(
			'id'		 => 'products-titlearea-title-color',
			'type'		 => 'color_rgba',
			'title'		 => esc_html__( 'Title text color', '5th-avenue' ),
			'required'	 => array(
				array( 'products-titlearea-type', '=', 'hero' ),
				array( 'products-titlearea-show', '=', '1' ),
			),
			'default'	 => array(
				'color'	 => '#000000',
				'alpha'	 => '1',
			),
		),
		array(
			'id'		 => 'products-titlearea-subtitle-color',
			'type'		 => 'color_rgba',
			'title'		 => esc_html__( 'Subtitle text color', '5th-avenue' ),
			'required'	 => array(
				array( 'products-titlearea-type', '=', 'hero' ),
				array( 'products-titlearea-show', '=', '1' ),
			),
			'default'	 => array(
				'color'	 => '#000000',
				'alpha'	 => '1',
			),
		),
		array(
			'id'		 => 'products-titlearea-text-above',
			'type'		 => 'text',
			'title'		 => esc_html__( 'Title area sub title', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'You can add a short line of text just above the title', '5th-avenue' ),
			'required'	 => array(
				array( 'products-titlearea-type', '!=', 'revslider' ),
				array( 'products-titlearea-show', '=', '1' ),
			),
		),
		array(
			'id'		 => 'products-titlearea-hero-additional-content',
			'type'		 => 'editor',
			'title'		 => esc_html__( 'Header additional content', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'You can add any content to the header area including shortcodes.', '5th-avenue' ),
			'required'	 => array(
				array( 'products-titlearea-type', '=', 'hero' ),
				array( 'products-titlearea-show', '=', '1' ),
			),
		),
		array(
			'id'					 => 'products-titlearea-background',
			'type'					 => 'background',
			'title'					 => esc_html__( 'Title Area Background', '5th-avenue' ),
			'subtitle'				 => esc_html__( 'You can set background image and color for title area.', '5th-avenue' ),
			'required'				 => array(
				array( 'products-titlearea-type', '=', 'hero' ),
				array( 'products-titlearea-show', '=', '1' ),
			),
			'background-repeat'		 => false,
			'background-attachment'	 => false,
			'background-position'	 => false,
			'background-size'		 => false,
		),
		array(
			'id'			 => 'products-titlearea-hero-height',
			'type'			 => 'dimensions',
			'title'			 => esc_html__( 'Hero Heading Height', '5th-avenue' ),
			'units'			 => array( 'px' ), // You can specify a unit value. Possible: px, em, %
			'units_extended' => 'true', // Allow users to select any type of unit.
			'required'		 => array(
				array( 'products-titlearea-type', '=', 'hero' ),
				array( 'products-titlearea-show', '=', '1' ),
			),
			'width'			 => false,
			'default'		 => array(
				'height' => 600,
			),
		),
		array(
			'id'		 => 'products-titlearea-hero-effect',
			'type'		 => 'button_set',
			'title'		 => esc_html__( 'Hero Heading Effect', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'None = title area scrolls with content. Fixed =title area stay on the same position, content scrolls over the title area.', '5th-avenue' ),
			'required'	 => array(
				array( 'products-titlearea-type', '=', 'hero' ),
				array( 'products-titlearea-show', '=', '1' ),
			),
			'options'	 => array(
				'none'		 => esc_html__( 'None', '5th-avenue' ),
				'parallax'	 => esc_html__( 'Parallax', '5th-avenue' ),
				'parallax2'	 => esc_html__( 'Parallax Bg', '5th-avenue' ),
				'fixed'		 => esc_html__( 'Fixed', '5th-avenue' ),
			),
			'default'	 => 'parallax',
		),
		array(
			'id'		 => 'products-titlearea-revslider-sliders-alias',
			'type'		 => 'select',
			'title'		 => esc_html__( 'Revolution Slider Alias', '5th-avenue' ),
			'subtitle'	 => esc_html__( 'Choose a Revolutions Slider to use on top of the page.', '5th-avenue' ),
			'required'	 => array(
				array( 'products-titlearea-type', '=', 'revslider' ),
				array( 'products-titlearea-show', '=', '1' ),
			),
			'options'	 => $rev_slider_all_aliases,
		),
		array(
			'id'		 => 'products-titlearea-hero-overlay-color',
			'type'		 => 'color',
			'title'		 => esc_html__( 'Hero Overlay color', '5th-avenue' ),
			'required'	 => array(
				array( 'products-titlearea-type', '=', 'hero' ),
				array( 'products-titlearea-show', '=', '1' ),
			),
			'default'	 => '#000000',
		),
		array(
			'id'			 => 'products-titlearea-hero-overlay-opacity',
			'type'			 => 'slider',
			'title'			 => esc_html__( 'Hero Overlay Opacity %', '5th-avenue' ),
			'required'		 => array(
				array( 'products-titlearea-type', '=', 'hero' ),
				array( 'products-titlearea-show', '=', '1' ),
			),
			'min'			 => 0,
			'step'			 => 1,
			'max'			 => 90,
			'display_value'	 => 'text',
			'default'		 => 40,
		),
		array(
			'id'		 => 'products-titlearea-meta',
			'type'		 => 'switch',
			'title'		 => esc_html__( 'Show Categories on Shop page', '5th-avenue' ),
			'required'	 => array(
				array( 'pages-titlearea-type', '!=', 'revslider' ),
				array( 'pages-titlearea-show', '=', '1' ),
			),
			'on'		 => esc_html__( 'Yes', '5th-avenue' ),
			'off'		 => esc_html__( 'No', '5th-avenue' ),
			'default'	 => true,
		),
	),
);

