<?php
/**
 * Available filters for extending Merlin WP.
 *
 * @package   Merlin WP
 * @version   @@pkg.version
 * @link      https://merlinwp.com/
 * @author    Rich Tabor, from ThemeBeans.com & the team at ProteusThemes.com
 * @copyright Copyright (c) 2018, Merlin WP of Inventionn LLC
 * @license   Licensed GPLv3 for Open Source Use
 */

defined( 'ABSPATH' ) || exit;

/**
 * Custom content for the generated child theme's functions.php file.
 *
 * @param string $output Generated content.
 * @param string $slug Parent theme slug.
 */
function prefix_generate_child_functions_php( $output, $slug ) {

	$slug_no_hyphens = strtolower( preg_replace( '#[^a-zA-Z]#', '', $slug ) );

	$output = "
		<?php
		/**
		 * Theme functions and definitions.
		 * This child theme was generated by Merlin WP.
		 *
		 * @link https://developer.wordpress.org/themes/basics/theme-functions/
		 */

		/*
		 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
		 * you will have to make sure to maintain all of the parent theme dependencies.
		 *
		 * Make sure you're using the correct handle for loading the parent theme's styles.
		 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
		 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
		 *
		 * @link https://codex.wordpress.org/Child_Themes
		 */
		function {$slug_no_hyphens}_child_enqueue_styles() {
			\$suffix_style = defined( 'STYLE_DEBUG' ) && STYLE_DEBUG || ! av5_get_option( 'min-css' ) ? '' : '.min';
			wp_enqueue_style( '{$slug}-style' , get_template_directory_uri() . '/style' . \$suffix_style . '.css' );
			wp_enqueue_style( '{$slug}-child-style',
				get_stylesheet_directory_uri() . '/style.css',
				array( '{$slug}-style' ),
				wp_get_theme()->get('Version')
			);
		}

		add_action(  'wp_enqueue_scripts', '{$slug_no_hyphens}_child_enqueue_styles' );\n
	";

	// Let's remove the tabs so that it displays nicely.
	$output = trim( preg_replace( '/\t+/', '', $output ) );

	// Filterable return.
	return $output;
}

add_filter( 'merlin_generate_child_functions_php', 'prefix_generate_child_functions_php', 10, 2 );

/**
 * Define the demo import files (local files).
 *
 * You have to use the same filter as in above example,
 * but with a slightly different array keys: local_*.
 * The values have to be absolute paths (not URLs) to your import files.
 * To use local import files, that reside in your theme folder,
 * please use the below code.
 * Note: make sure your import files are readable!
 */
function av5_merlin_local_import_files() {
	return array(
		array(
			'import_file_name'				 => 'clean-theme',
			'local_import_customizer_file'	 => trailingslashit( get_template_directory() ) . 'inc/demo-data-clean/customizer.dat',
			'local_import_redux'			 => array(
				array(
					'file_path'		 => trailingslashit( get_template_directory() ) . 'inc/demo-data-clean/redux.json',
					'option_name'	 => apply_filters( 'av5_redux_name', 'lid_av5' ),
				),
			),
		),
	);
}

add_filter( 'merlin_import_files', 'av5_merlin_local_import_files' );

/**
 * Execute custom code after the whole import has finished.
 *
 * @param mixed $selected_import_index Imported demo.
 */
function av5_merlin_after_import_setup( $selected_import_index ) {
	// Assign menus to their locations.
	switch ( $selected_import_index ) {
		default:
			av5_merlin_update_nav_menu( null, $selected_import_index );
			break;
	}
	// Assign front page and posts page (blog page).
	switch ( $selected_import_index ) {
		case 'wbc-import-demo-shirts':
			av5_merlin_update_on_front_page( array(
				'page_on_front'	 => 'Home - Brown',
				'page_for_posts' => 'Journal',
			), $selected_import_index );
			break;
		case 'wbc-import-demo-fave':
		case 'wbc-import-demo-manshop':
			av5_merlin_update_on_front_page( array(
				'page_on_front'	 => 'Home',
				'page_for_posts' => 'The Journal',
			), $selected_import_index );
			break;
		default:
			av5_merlin_update_on_front_page( null, $selected_import_index );
			break;
	}
}

add_action( 'merlin_after_all_import', 'av5_merlin_after_import_setup' );

if ( ! function_exists( 'av5_merlin_update_on_front_page' ) ) {

	/**
	 * Set Menu Position Wordpress
	 *
	 * @param array $menus Nemu name associatet.
	 * @param mixed $selected_import_index Imported demo.
	 */
	function av5_merlin_update_nav_menu( $menus = null, $selected_import_index = '' ) {
		if ( ! current_theme_supports( 'menus' ) ) {
			return;
		}
		$locations = get_registered_nav_menus();
		if ( empty( $locations ) ) {
			return;
		}
		$menu_locations = get_nav_menu_locations();
		foreach ( $locations as $menu_key => $menu_title ) {
			$menu = get_term_by( 'name', $menu_title, 'nav_menu' ); // @codingStandardsIgnoreLine WordPress.VIP.RestrictedFunctions.get_term_by
			if ( $menu instanceof WP_Term ) {
				$menu_locations[ $menu_key ] = $menu->term_id;
			}
		}

		if ( ! empty( $menus ) && is_array( $menus ) ) {
			foreach ( $menus as $menu_key => $menu_title ) {
				if ( array_key_exists( $menu_key, $locations ) ) {
					$menu = get_term_by( 'name', $menu_title, 'nav_menu' ); // @codingStandardsIgnoreLine WordPress.VIP.RestrictedFunctions.get_term_by
					if ( $menu instanceof WP_Term ) {
						$menu_locations[ $menu_key ] = $menu->term_id;
					}
				}
			}
		}

		$menu_locations = apply_filters( 'av5_merlin_update_on_front_page', $menu_locations, $selected_import_index );
		set_theme_mod( 'nav_menu_locations', $menu_locations );
	}
} // End if().

if ( ! function_exists( 'av5_merlin_update_on_front_page' ) ) {

	/**
	 * Set Reading Settings Wordpress
	 *
	 * @param array $pages Page name associatet.
	 * @param mixed $selected_import_index Imported demo.
	 */
	function av5_merlin_update_on_front_page( $pages = null, $selected_import_index = '' ) {
		$pages_ids = array(
			'page_on_front'	 => 0,
			'page_for_posts' => 0,
		);
		if ( ! empty( $pages ) && is_array( $pages ) ) {
			foreach ( $pages as $page_key => $page_title ) {
				if ( array_key_exists( $page_key, $pages_ids ) ) {
					$page = get_page_by_title( $page_title ); // @codingStandardsIgnoreLine WordPress.VIP.RestrictedFunctions.get_page_by_title
					if ( ! empty( $page ) ) {
						$pages_ids[ $page_key ] = $page->ID;
					}
				}
			}
		}

		$pages_ids	 = apply_filters( 'av5_merlin_update_on_front_page', $pages_ids, $selected_import_index );
		$_pages_ids	 = array_filter( $pages_ids );
		update_option( 'show_on_front', ! empty( $_pages_ids ) ? 'page' : 'posts' );
		foreach ( $pages_ids as $page_key => $pages_ids ) {
			update_option( $page_key, $pages_ids );
		}
	}
}

if ( ! function_exists( 'av5_remove_redux_welcome' ) ) {

	/**
	 * Remove redux welcome
	 */
	function av5_remove_redux_welcome() {
		av5_remove_action( 'init', array( 'Redux_Welcome', 'do_redirect' ) );
	}
}

add_action( 'redux/loaded', 'av5_remove_redux_welcome', 15 );


if ( ! function_exists( 'av5_remove_metabox_welcome' ) ) {

	/**
	 * Remove redux welcome
	 */
	function av5_remove_metabox_welcome() {
		av5_remove_action( 'activated_plugin', array( 'RWMB_About', 'redirect' ), 10 );
	}
}

add_action( 'activated_plugin', 'av5_remove_metabox_welcome', 9 );
